Repository QuickRelease/django-async-downloads, pull requests merged in 2022-02, with the labels that each got.

#22 feat: Add support for WebSockets
  README.md
  async_downloads/cache.py
  async_downloads/settings.py
  async_downloads/shortcuts.py
  async_downloads/static/css/async_downloads.css
  async_downloads/static/js/async_downloads.js
  async_downloads/static/js/ws_async_downloads.js
  async_downloads/templates/async_downloads/downloads.html
  async_downloads/views.py
  async_downloads/ws_consumers.py
  setup.py
Labels: feat, minor

#24 fix: add url for completed download
  async_downloads/ws_consumers.py
Labels: fix

#25 build: bump version to 0.4.1
  setup.py
Labels: skip-changelog, build
