Repository QuickRelease/django-async-downloads, pull requests merged in 2022-03, with the labels that each got.

#26 feat: reject ws connection for anonymous users
  async_downloads/ws_consumers.py
  setup.py
Labels: feat, minor

#28 fix: flush remaining bytes in the buffer
  async_downloads/cache.py
Labels: fix

#29 build: bump version to 0.4.3
  setup.py
Labels: skip-changelog, build
